# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Amplify CLI
      run: npm install -g @aws-amplify/cli
    - name: Install dependencies
      run: npm install
    - name: Build project
      env:
        CI: false 
      run: npm run build --if-present
    - name: Run tests and generate JSON report
      run: |
        npm run test -- --json --outputFile=test-report.json

    - name: Calculate pass percentage
      id: calculate-pass-percentage
      run: |
        totalTests=$(jq '.numTotalTests' test-report.json)
        passedTests=$(jq '.numPassedTests' test-report.json)
        passPercentage=$((passedTests * 100 / totalTests))
        echo "Pass Percentage: $passPercentage%"

    - name: Check if pass percentage meets threshold
      if: env.pass-percentage < 50
      run: |
        echo "Test pass percentage is below the threshold. Failing the build."
        exit 1
